### ISSUE TITLE
https://www.openstandard.org/contact-us/

### ISSUE THREAD

**Issue by codepo8** [mozilla/theopenstandard#78]
The contact page is broken

**Comment by bensternthal** [comment]
Looks like a bug here that is not playing well with the contact us plugin.
https://github.com/mozilla/theopenstandard/blob/master/themes/theopenstandard/content-filters.php

Will take a look Monday at a quick fix or if no quick fix and the site is going to remain in hibernation for a long time I will remove the link from the footer.

**Comment by bensternthal** [comment]
Moving this discussion to bugzilla:

https://bugzilla.mozilla.org/show_bug.cgi?id=1125573
